/**
 * data.js
 * Single source of truth for the product catalog and site navigation.
 * Every page reads from PRODUCTS instead of hard-coding product info,
 * so adding/editing a product only requires changing this one file.
 */

// Sizes offered on every product (matches the real site's XXS-XXL range).
const SIZES = ["XXS", "XS", "S", "M", "L", "XL", "XXL"];

// Categories and fabrics shown in the navigation, in display order.
const CATEGORIES = ["Tops", "Skirts", "Dresses", "Trousers", "Vests", "Co-ord Sets"];
const FABRICS = ["Handwoven Silk", "Natural Crepe"];

// Helper to turn a display name into a URL-safe slug, e.g. "Co-ord Sets" -> "co-ord-sets"
function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const PRODUCTS = [
  // ---- Natural Crepe collection (best sellers) ----
  {
    slug: "crepe-silk-pintuck-straight-skirt",
    images: ["images/products/crepe-silk-pintuck-straight-skirt__pageant-blue-1.jpg", "images/products/crepe-silk-pintuck-straight-skirt__pageant-blue-2.jpg", "images/products/crepe-silk-pintuck-straight-skirt__pageant-blue-3.jpg"],
    imagesByColor: {
      "Pageant Blue": ["images/products/crepe-silk-pintuck-straight-skirt__pageant-blue-1.jpg", "images/products/crepe-silk-pintuck-straight-skirt__pageant-blue-2.jpg", "images/products/crepe-silk-pintuck-straight-skirt__pageant-blue-3.jpg"],
    },
    launchedAt: "2024-11-02",
    name: "Crepe Silk Pintuck Straight Skirt",
    category: "Skirts",
    fabric: "Natural Crepe",
    price: 255,
    colors: ["Pageant Blue"],
    length: "Calf",
    bestSeller: true,
    description: "A straight-cut skirt in soft crepe with fine pintuck detailing at the waist for a clean, tailored line that moves easily from desk to dinner.",
  },
  {
    slug: "crepe-silk-pleated-dress",
    images: ["images/products/crepe-silk-pleated-dress__pageant-blue-1.jpg", "images/products/crepe-silk-pleated-dress__pageant-blue-2.jpg", "images/products/crepe-silk-pleated-dress__pageant-blue-3.jpg"],
    imagesByColor: {
      "Pageant Blue": ["images/products/crepe-silk-pleated-dress__pageant-blue-1.jpg", "images/products/crepe-silk-pleated-dress__pageant-blue-2.jpg", "images/products/crepe-silk-pleated-dress__pageant-blue-3.jpg"],
      "Potent Purple": ["images/products/crepe-silk-pleated-dress__potent-purple-1.jpg"],
      "Purple Potion": ["images/products/crepe-silk-pleated-dress__purple-potion-1.jpg", "images/products/crepe-silk-pleated-dress__purple-potion-2.jpg", "images/products/crepe-silk-pleated-dress__purple-potion-3.jpg"],
    },
    launchedAt: "2024-11-18",
    name: "Crepe Silk Pleated Dress",
    category: "Dresses",
    fabric: "Natural Crepe",
    price: 270,
    colors: ["Pageant Blue", "Potent Purple", "Purple Potion"],
    length: "Knee",
    bestSeller: true,
    description: "A sleeveless crepe dress with soft pleats at the bust that release into a gentle flare, striking a balance between everyday ease and evening polish.",
  },
  {
    slug: "crepe-silk-textured-long-top",
    images: ["images/products/crepe-silk-textured-long-top__pageant-blue-1.jpg", "images/products/crepe-silk-textured-long-top__pageant-blue-2.jpg", "images/products/crepe-silk-textured-long-top__pageant-blue-3.jpg"],
    imagesByColor: {
      "Pageant Blue": ["images/products/crepe-silk-textured-long-top__pageant-blue-1.jpg", "images/products/crepe-silk-textured-long-top__pageant-blue-2.jpg", "images/products/crepe-silk-textured-long-top__pageant-blue-3.jpg"],
      "Kombu Green": ["images/products/crepe-silk-textured-long-top__kombu-green-1.jpg"],
    },
    launchedAt: "2024-12-05",
    name: "Crepe Silk Textured Long Top",
    category: "Tops",
    fabric: "Natural Crepe",
    price: 320,
    colors: ["Pageant Blue", "Kombu Green"],
    length: "Regular",
    bestSeller: true,
    description: "An elongated top in textured crepe designed to layer cleanly under a blazer or stand alone with tailored trousers.",
  },
  {
    slug: "crepe-silk-vest",
    images: ["images/products/crepe-silk-vest__pageant-blue-1.jpg", "images/products/crepe-silk-vest__pageant-blue-2.jpg", "images/products/crepe-silk-vest__pageant-blue-3.jpg"],
    imagesByColor: {
      "Pageant Blue": ["images/products/crepe-silk-vest__pageant-blue-1.jpg", "images/products/crepe-silk-vest__pageant-blue-2.jpg", "images/products/crepe-silk-vest__pageant-blue-3.jpg"],
    },
    launchedAt: "2024-12-20",
    name: "Crepe Silk Vest",
    category: "Vests",
    fabric: "Natural Crepe",
    price: 225,
    colors: ["Pageant Blue"],
    length: "Regular",
    bestSeller: true,
    description: "A structured crepe vest cut for effortless layering, equally at home over a shirt or worn on its own.",
  },
  {
    slug: "crepe-silk-vest-and-skirt-set",
    images: ["images/products/crepe-silk-vest-and-skirt-set__pageant-blue-1.jpg", "images/products/crepe-silk-vest-and-skirt-set__pageant-blue-2.jpg", "images/products/crepe-silk-vest-and-skirt-set__pageant-blue-3.jpg"],
    imagesByColor: {
      "Pageant Blue": ["images/products/crepe-silk-vest-and-skirt-set__pageant-blue-1.jpg", "images/products/crepe-silk-vest-and-skirt-set__pageant-blue-2.jpg", "images/products/crepe-silk-vest-and-skirt-set__pageant-blue-3.jpg"],
    },
    launchedAt: "2025-01-10",
    name: "Crepe Silk Vest and Skirt Set",
    category: "Co-ord Sets",
    fabric: "Natural Crepe",
    price: 475,
    colors: ["Pageant Blue"],
    length: "Calf",
    bestSeller: false,
    description: "A coordinated vest and skirt in matching crepe, built as a one-decision outfit for days that run long.",
  },

  // ---- Handwoven Silk collection ----
  {
    slug: "mulberry-silk-overlap-vest-and-pintuck-trouser-set",
    images: ["images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__chocolate-truffle-1.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__chocolate-truffle-2.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__chocolate-truffle-3.jpg"],
    imagesByColor: {
      "Chocolate Truffle": ["images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__chocolate-truffle-1.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__chocolate-truffle-2.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__chocolate-truffle-3.jpg"],
      "Sky Captain": ["images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__sky-captain-1.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__sky-captain-2.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__sky-captain-3.jpg"],
      "Fig": ["images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__fig-1.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__fig-2.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__fig-3.jpg"],
      "Fudge": ["images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__fudge-1.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__fudge-2.jpg", "images/products/mulberry-silk-overlap-vest-and-pintuck-trouser-set__fudge-3.jpg"],
    },
    launchedAt: "2025-01-28",
    name: "Mulberry Silk Overlap Vest and Pintuck Trouser Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 465,
    colors: ["Chocolate Truffle", "Sky Captain", "Fig", "Fudge"],
    length: "Regular",
    bestSeller: false,
    description: "An overlap vest paired with pintuck trousers, both cut from handwoven mulberry silk for a considered head-to-toe look.",
  },
  {
    slug: "mulberry-silk-asymmetrical-wrap-skirt",
    images: ["images/products/mulberry-silk-asymmetrical-wrap-skirt__forest-night-1.jpg", "images/products/mulberry-silk-asymmetrical-wrap-skirt__forest-night-2.jpg", "images/products/mulberry-silk-asymmetrical-wrap-skirt__forest-night-3.jpg"],
    imagesByColor: {
      "Forest Night": ["images/products/mulberry-silk-asymmetrical-wrap-skirt__forest-night-1.jpg", "images/products/mulberry-silk-asymmetrical-wrap-skirt__forest-night-2.jpg", "images/products/mulberry-silk-asymmetrical-wrap-skirt__forest-night-3.jpg"],
      "Nomad": ["images/products/mulberry-silk-asymmetrical-wrap-skirt__nomad-1.jpg", "images/products/mulberry-silk-asymmetrical-wrap-skirt__nomad-2.jpg", "images/products/mulberry-silk-asymmetrical-wrap-skirt__nomad-3.jpg"],
      "Duffel Bag": ["images/products/mulberry-silk-asymmetrical-wrap-skirt__duffel-bag-1.jpg"],
      "Fig": ["images/products/mulberry-silk-asymmetrical-wrap-skirt__fig-1.jpg", "images/products/mulberry-silk-asymmetrical-wrap-skirt__fig-2.jpg", "images/products/mulberry-silk-asymmetrical-wrap-skirt__fig-3.jpg"],
    },
    launchedAt: "2025-02-14",
    name: "Mulberry Silk Asymmetrical Wrap Skirt",
    category: "Skirts",
    fabric: "Handwoven Silk",
    price: 320,
    colors: ["Forest Night", "Nomad", "Duffel Bag", "Fig"],
    length: "Calf",
    bestSeller: false,
    description: "A wrap skirt with an asymmetrical hem in handwoven silk, offering movement without sacrificing a tailored silhouette.",
  },
  {
    slug: "mulberry-silk-wide-neck-vest-and-pant-set",
    images: ["images/products/mulberry-silk-wide-neck-vest-and-pant-set__pure-cashmere-1.jpg", "images/products/mulberry-silk-wide-neck-vest-and-pant-set__pure-cashmere-2.jpg", "images/products/mulberry-silk-wide-neck-vest-and-pant-set__pure-cashmere-3.jpg"],
    imagesByColor: {
      "Pure Cashmere": ["images/products/mulberry-silk-wide-neck-vest-and-pant-set__pure-cashmere-1.jpg", "images/products/mulberry-silk-wide-neck-vest-and-pant-set__pure-cashmere-2.jpg", "images/products/mulberry-silk-wide-neck-vest-and-pant-set__pure-cashmere-3.jpg"],
      "Duffel Bag": ["images/products/mulberry-silk-wide-neck-vest-and-pant-set__duffel-bag-1.jpg", "images/products/mulberry-silk-wide-neck-vest-and-pant-set__duffel-bag-2.jpg", "images/products/mulberry-silk-wide-neck-vest-and-pant-set__duffel-bag-3.jpg"],
      "Ebony": ["images/products/mulberry-silk-wide-neck-vest-and-pant-set__ebony-1.jpg", "images/products/mulberry-silk-wide-neck-vest-and-pant-set__ebony-2.jpg"],
    },
    launchedAt: "2025-03-01",
    name: "Mulberry Silk Wide Neck Vest and Pant Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 490,
    colors: ["Pure Cashmere", "Duffel Bag", "Ebony"],
    length: "Regular",
    bestSeller: false,
    description: "A wide-neck vest and matching pant in handwoven silk, designed as a single grab-and-go set for packed weeks.",
  },
  {
    slug: "mulberry-silk-vest-and-skirt-set",
    images: ["images/products/mulberry-silk-vest-and-skirt-set__burnt-russet-1.jpg", "images/products/mulberry-silk-vest-and-skirt-set__burnt-russet-2.jpg", "images/products/mulberry-silk-vest-and-skirt-set__burnt-russet-3.jpg"],
    imagesByColor: {
      "Burnt Russet": ["images/products/mulberry-silk-vest-and-skirt-set__burnt-russet-1.jpg", "images/products/mulberry-silk-vest-and-skirt-set__burnt-russet-2.jpg", "images/products/mulberry-silk-vest-and-skirt-set__burnt-russet-3.jpg"],
      "Nomad": ["images/products/mulberry-silk-vest-and-skirt-set__nomad-1.jpg", "images/products/mulberry-silk-vest-and-skirt-set__nomad-2.jpg", "images/products/mulberry-silk-vest-and-skirt-set__nomad-3.jpg"],
    },
    launchedAt: "2025-03-19",
    name: "Mulberry Silk Vest and Skirt Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 420,
    colors: ["Burnt Russet", "Nomad"],
    length: "Calf",
    bestSeller: false,
    description: "A vest and skirt set in handwoven silk, pairing a fitted top half with a fluid, easy-moving skirt.",
  },
  {
    slug: "mulberry-silk-vest",
    images: ["images/products/mulberry-silk-vest__burnt-russet-1.jpg", "images/products/mulberry-silk-vest__burnt-russet-2.jpg", "images/products/mulberry-silk-vest__burnt-russet-3.jpg"],
    imagesByColor: {
      "Burnt Russet": ["images/products/mulberry-silk-vest__burnt-russet-1.jpg", "images/products/mulberry-silk-vest__burnt-russet-2.jpg", "images/products/mulberry-silk-vest__burnt-russet-3.jpg"],
      "Nomad": ["images/products/mulberry-silk-vest__nomad-1.jpg"],
    },
    launchedAt: "2025-04-07",
    name: "Mulberry Silk Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 200,
    colors: ["Burnt Russet", "Sepia Tint", "Nomad"],
    length: "Regular",
    bestSeller: false,
    description: "A simply cut vest in handwoven mulberry silk, meant to be worn on repeat under jackets or alone.",
  },
  {
    slug: "mulberry-silk-v-neck-top-with-kantha-embroidery",
    images: ["images/products/mulberry-silk-v-neck-top-with-kantha-embroidery__pure-cashmere-1.jpg", "images/products/mulberry-silk-v-neck-top-with-kantha-embroidery__pure-cashmere-2.jpg", "images/products/mulberry-silk-v-neck-top-with-kantha-embroidery__pure-cashmere-3.jpg"],
    imagesByColor: {
      "Pure Cashmere": ["images/products/mulberry-silk-v-neck-top-with-kantha-embroidery__pure-cashmere-1.jpg", "images/products/mulberry-silk-v-neck-top-with-kantha-embroidery__pure-cashmere-2.jpg", "images/products/mulberry-silk-v-neck-top-with-kantha-embroidery__pure-cashmere-3.jpg"],
    },
    launchedAt: "2025-04-22",
    name: "Mulberry Silk V-Neck Top with Kantha Embroidery",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 290,
    colors: ["Pure Cashmere"],
    length: "Regular",
    bestSeller: false,
    description: "A V-neck top finished with hand-stitched kantha embroidery, adding quiet texture to a minimal silhouette.",
  },
  {
    slug: "mulberry-silk-pintuck-cap-sleeve-top",
    images: ["images/products/mulberry-silk-pintuck-cap-sleeve-top__chocolate-truffle-1.jpg", "images/products/mulberry-silk-pintuck-cap-sleeve-top__chocolate-truffle-2.jpg", "images/products/mulberry-silk-pintuck-cap-sleeve-top__chocolate-truffle-3.jpg"],
    imagesByColor: {
      "Chocolate Truffle": ["images/products/mulberry-silk-pintuck-cap-sleeve-top__chocolate-truffle-1.jpg", "images/products/mulberry-silk-pintuck-cap-sleeve-top__chocolate-truffle-2.jpg", "images/products/mulberry-silk-pintuck-cap-sleeve-top__chocolate-truffle-3.jpg"],
    },
    launchedAt: "2025-05-09",
    name: "Mulberry Silk Pintuck Cap Sleeve Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Chocolate Truffle"],
    length: "Regular",
    bestSeller: false,
    description: "A cap-sleeve top with pintuck detail at the shoulder, cut from handwoven silk for a soft structured drape.",
  },
  {
    slug: "mulberry-silk-pintuck-wrap-skirt",
    images: ["images/products/mulberry-silk-pintuck-wrap-skirt__fudge-1.jpg", "images/products/mulberry-silk-pintuck-wrap-skirt__fudge-2.jpg", "images/products/mulberry-silk-pintuck-wrap-skirt__fudge-3.jpg"],
    imagesByColor: {
      "Fudge": ["images/products/mulberry-silk-pintuck-wrap-skirt__fudge-1.jpg", "images/products/mulberry-silk-pintuck-wrap-skirt__fudge-2.jpg", "images/products/mulberry-silk-pintuck-wrap-skirt__fudge-3.jpg"],
      "Chocolate Truffle": ["images/products/mulberry-silk-pintuck-wrap-skirt__chocolate-truffle-1.jpg", "images/products/mulberry-silk-pintuck-wrap-skirt__chocolate-truffle-2.jpg", "images/products/mulberry-silk-pintuck-wrap-skirt__chocolate-truffle-3.jpg"],
      "Ebony": ["images/products/mulberry-silk-pintuck-wrap-skirt__ebony-1.jpg", "images/products/mulberry-silk-pintuck-wrap-skirt__ebony-2.jpg", "images/products/mulberry-silk-pintuck-wrap-skirt__ebony-3.jpg"],
    },
    launchedAt: "2025-05-27",
    name: "Mulberry Silk Pintuck Wrap Skirt",
    category: "Skirts",
    fabric: "Handwoven Silk",
    price: 270,
    colors: ["Fudge", "Chocolate Truffle", "Ebony"],
    length: "Calf",
    bestSeller: false,
    description: "A wrap skirt with pintuck detailing at the waistband, designed to sit smoothly under a fitted top.",
  },
  {
    slug: "mulberry-silk-pintuck-wide-neck-vest",
    images: ["images/products/mulberry-silk-pintuck-wide-neck-vest__forest-night-1.jpg", "images/products/mulberry-silk-pintuck-wide-neck-vest__forest-night-2.jpg"],
    imagesByColor: {
      "Forest Night": ["images/products/mulberry-silk-pintuck-wide-neck-vest__forest-night-1.jpg", "images/products/mulberry-silk-pintuck-wide-neck-vest__forest-night-2.jpg"],
      "Pure Cashmere": ["images/products/mulberry-silk-pintuck-wide-neck-vest__pure-cashmere-1.jpg", "images/products/mulberry-silk-pintuck-wide-neck-vest__pure-cashmere-2.jpg", "images/products/mulberry-silk-pintuck-wide-neck-vest__pure-cashmere-3.jpg"],
      "Duffel Bag": ["images/products/mulberry-silk-pintuck-wide-neck-vest__duffel-bag-1.jpg", "images/products/mulberry-silk-pintuck-wide-neck-vest__duffel-bag-2.jpg"],
      "Ebony": ["images/products/mulberry-silk-pintuck-wide-neck-vest__ebony-1.jpg", "images/products/mulberry-silk-pintuck-wide-neck-vest__ebony-2.jpg"],
    },
    launchedAt: "2025-06-12",
    name: "Mulberry Silk Pintuck Wide Neck Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Forest Night", "Pure Cashmere", "Duffel Bag", "Ebony"],
    length: "Regular",
    bestSeller: false,
    description: "A wide-neck vest with fine pintuck detailing, cut for a clean line across the shoulders.",
  },
  {
    slug: "mulberry-silk-pintuck-vest",
    images: ["images/products/mulberry-silk-pintuck-vest__sky-captain-1.jpg", "images/products/mulberry-silk-pintuck-vest__sky-captain-2.jpg", "images/products/mulberry-silk-pintuck-vest__sky-captain-3.jpg"],
    imagesByColor: {
      "Sky Captain": ["images/products/mulberry-silk-pintuck-vest__sky-captain-1.jpg", "images/products/mulberry-silk-pintuck-vest__sky-captain-2.jpg", "images/products/mulberry-silk-pintuck-vest__sky-captain-3.jpg"],
    },
    launchedAt: "2025-06-30",
    name: "Mulberry Silk Pintuck Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Sky Captain"],
    length: "Regular",
    bestSeller: false,
    description: "A pintuck vest in handwoven silk, built as an easy layer over tops and dresses alike.",
  },
  {
    slug: "mulberry-silk-pintuck-trousers",
    images: ["images/products/mulberry-silk-pintuck-trousers__chocolate-truffle-1.jpg", "images/products/mulberry-silk-pintuck-trousers__chocolate-truffle-2.jpg", "images/products/mulberry-silk-pintuck-trousers__chocolate-truffle-3.jpg"],
    imagesByColor: {
      "Chocolate Truffle": ["images/products/mulberry-silk-pintuck-trousers__chocolate-truffle-1.jpg", "images/products/mulberry-silk-pintuck-trousers__chocolate-truffle-2.jpg", "images/products/mulberry-silk-pintuck-trousers__chocolate-truffle-3.jpg"],
      "Ebony": ["images/products/mulberry-silk-pintuck-trousers__ebony-1.jpg", "images/products/mulberry-silk-pintuck-trousers__ebony-2.jpg", "images/products/mulberry-silk-pintuck-trousers__ebony-3.jpg"],
      "Forest Night": ["images/products/mulberry-silk-pintuck-trousers__forest-night-1.jpg", "images/products/mulberry-silk-pintuck-trousers__forest-night-2.jpg", "images/products/mulberry-silk-pintuck-trousers__forest-night-3.jpg"],
      "Pure Cashmere": ["images/products/mulberry-silk-pintuck-trousers__pure-cashmere-1.jpg", "images/products/mulberry-silk-pintuck-trousers__pure-cashmere-2.jpg", "images/products/mulberry-silk-pintuck-trousers__pure-cashmere-3.jpg"],
      "Moonless Night": ["images/products/mulberry-silk-pintuck-trousers__moonless-night-1.jpg"],
      "Nomad": ["images/products/mulberry-silk-pintuck-trousers__nomad-1.jpg", "images/products/mulberry-silk-pintuck-trousers__nomad-2.jpg", "images/products/mulberry-silk-pintuck-trousers__nomad-3.jpg"],
      "Fig": ["images/products/mulberry-silk-pintuck-trousers__fig-1.jpg", "images/products/mulberry-silk-pintuck-trousers__fig-2.jpg", "images/products/mulberry-silk-pintuck-trousers__fig-3.jpg"],
      "Fudge": ["images/products/mulberry-silk-pintuck-trousers__fudge-1.jpg", "images/products/mulberry-silk-pintuck-trousers__fudge-2.jpg", "images/products/mulberry-silk-pintuck-trousers__fudge-3.jpg"],
      "Duffel Bag": ["images/products/mulberry-silk-pintuck-trousers__duffel-bag-1.jpg", "images/products/mulberry-silk-pintuck-trousers__duffel-bag-2.jpg", "images/products/mulberry-silk-pintuck-trousers__duffel-bag-3.jpg"],
      "Sky Captain": ["images/products/mulberry-silk-pintuck-trousers__sky-captain-1.jpg", "images/products/mulberry-silk-pintuck-trousers__sky-captain-2.jpg"],
    },
    launchedAt: "2025-07-15",
    name: "Mulberry Silk Pintuck Trousers",
    category: "Trousers",
    fabric: "Handwoven Silk",
    price: 270,
    colors: [
      "Chocolate Truffle", "Ebony", "Forest Night", "Pure Cashmere",
      "Moonless Night", "Nomad", "Fig", "Fudge", "Duffel Bag", "Sky Captain",
    ],
    length: "Cropped",
    bestSeller: false,
    description: "Cropped pintuck trousers in handwoven silk, cut with a tailored waist and a relaxed leg.",
  },
  {
    slug: "mulberry-silk-pintuck-straight-skirt",
    images: ["images/products/mulberry-silk-pintuck-straight-skirt__burnt-russet-1.jpg", "images/products/mulberry-silk-pintuck-straight-skirt__burnt-russet-2.jpg", "images/products/mulberry-silk-pintuck-straight-skirt__burnt-russet-3.jpg"],
    imagesByColor: {
      "Burnt Russet": ["images/products/mulberry-silk-pintuck-straight-skirt__burnt-russet-1.jpg", "images/products/mulberry-silk-pintuck-straight-skirt__burnt-russet-2.jpg", "images/products/mulberry-silk-pintuck-straight-skirt__burnt-russet-3.jpg"],
      "Sky Captain": ["images/products/mulberry-silk-pintuck-straight-skirt__sky-captain-1.jpg", "images/products/mulberry-silk-pintuck-straight-skirt__sky-captain-2.jpg", "images/products/mulberry-silk-pintuck-straight-skirt__sky-captain-3.jpg"],
      "Nomad": ["images/products/mulberry-silk-pintuck-straight-skirt__nomad-1.jpg", "images/products/mulberry-silk-pintuck-straight-skirt__nomad-2.jpg", "images/products/mulberry-silk-pintuck-straight-skirt__nomad-3.jpg"],
    },
    launchedAt: "2025-08-03",
    name: "Mulberry Silk Pintuck Straight Skirt",
    category: "Skirts",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Burnt Russet", "Sky Captain", "Nomad"],
    length: "Knee",
    bestSeller: false,
    description: "A straight skirt with pintuck detail at the waist, offering a polished line for the office and beyond.",
  },
  {
    slug: "mulberry-silk-pintuck-overlap-vest",
    images: ["images/products/mulberry-silk-pintuck-overlap-vest__ebony-1.jpg", "images/products/mulberry-silk-pintuck-overlap-vest__ebony-2.jpg", "images/products/mulberry-silk-pintuck-overlap-vest__ebony-3.jpg"],
    imagesByColor: {
      "Ebony": ["images/products/mulberry-silk-pintuck-overlap-vest__ebony-1.jpg", "images/products/mulberry-silk-pintuck-overlap-vest__ebony-2.jpg", "images/products/mulberry-silk-pintuck-overlap-vest__ebony-3.jpg"],
      "Moonless Night": ["images/products/mulberry-silk-pintuck-overlap-vest__moonless-night-1.jpg", "images/products/mulberry-silk-pintuck-overlap-vest__moonless-night-2.jpg", "images/products/mulberry-silk-pintuck-overlap-vest__moonless-night-3.jpg"],
      "Pure Cashmere": ["images/products/mulberry-silk-pintuck-overlap-vest__pure-cashmere-1.jpg", "images/products/mulberry-silk-pintuck-overlap-vest__pure-cashmere-2.jpg"],
    },
    launchedAt: "2025-09-01",
    name: "Mulberry Silk Pintuck Overlap Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 215,
    colors: ["Ebony", "Moonless Night", "Pure Cashmere"],
    length: "Regular",
    bestSeller: false,
    description: "An overlap-front vest with pintuck detailing, designed to layer neatly over fitted tops.",
  },
  {
    slug: "mulberry-pintuck-vest-and-skirt-set",
    images: ["images/products/mulberry-pintuck-vest-and-skirt-set__sky-captain-1.jpg", "images/products/mulberry-pintuck-vest-and-skirt-set__sky-captain-2.jpg", "images/products/mulberry-pintuck-vest-and-skirt-set__sky-captain-3.jpg"],
    imagesByColor: {
      "Sky Captain": ["images/products/mulberry-pintuck-vest-and-skirt-set__sky-captain-1.jpg", "images/products/mulberry-pintuck-vest-and-skirt-set__sky-captain-2.jpg", "images/products/mulberry-pintuck-vest-and-skirt-set__sky-captain-3.jpg"],
    },
    launchedAt: "2025-10-05",
    name: "Mulberry Pintuck Vest and Skirt Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 440,
    colors: ["Sky Captain"],
    length: "Calf",
    bestSeller: false,
    description: "A matching pintuck vest and skirt set, made as a single considered outfit for busy days.",
  },
  {
    slug: "mulberry-silk-overlap-vest",
    images: ["images/products/mulberry-silk-overlap-vest__chocolate-truffle-1.jpg", "images/products/mulberry-silk-overlap-vest__chocolate-truffle-2.jpg", "images/products/mulberry-silk-overlap-vest__chocolate-truffle-3.jpg"],
    imagesByColor: {
      "Chocolate Truffle": ["images/products/mulberry-silk-overlap-vest__chocolate-truffle-1.jpg", "images/products/mulberry-silk-overlap-vest__chocolate-truffle-2.jpg", "images/products/mulberry-silk-overlap-vest__chocolate-truffle-3.jpg"],
      "Sky Captain": ["images/products/mulberry-silk-overlap-vest__sky-captain-1.jpg"],
      "Fudge": ["images/products/mulberry-silk-overlap-vest__fudge-1.jpg", "images/products/mulberry-silk-overlap-vest__fudge-2.jpg", "images/products/mulberry-silk-overlap-vest__fudge-3.jpg"],
      "Fig": ["images/products/mulberry-silk-overlap-vest__fig-1.jpg"],
    },
    launchedAt: "2025-11-12",
    name: "Mulberry Silk Overlap Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 200,
    colors: ["Chocolate Truffle", "Sky Captain", "Fudge", "Fig"],
    length: "Regular",
    bestSeller: false,
    description: "An overlap-front vest in handwoven silk, simple enough to wear year-round.",
  },
  {
    slug: "mulberry-silk-overlap-pintuck-vest-and-trouser-set",
    images: ["images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__ebony-1.jpg", "images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__ebony-2.jpg", "images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__ebony-3.jpg"],
    imagesByColor: {
      "Ebony": ["images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__ebony-1.jpg", "images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__ebony-2.jpg", "images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__ebony-3.jpg"],
      "Moonless Night": ["images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__moonless-night-1.jpg", "images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__moonless-night-2.jpg", "images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__moonless-night-3.jpg"],
      "Pure Cashmere": ["images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__pure-cashmere-1.jpg", "images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__pure-cashmere-2.jpg", "images/products/mulberry-silk-overlap-pintuck-vest-and-trouser-set__pure-cashmere-3.jpg"],
    },
    launchedAt: "2025-12-08",
    name: "Mulberry Silk Overlap Pintuck Vest and Trouser Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 475,
    colors: ["Ebony", "Moonless Night", "Pure Cashmere"],
    length: "Regular",
    bestSeller: false,
    description: "An overlap vest and pintuck trouser set in handwoven silk, built as a complete look in one order.",
  },
  {
    slug: "mulberry-silk-embroidered-wrap-skirt-set",
    images: ["images/products/mulberry-silk-embroidered-wrap-skirt-set__fudge-1.jpg", "images/products/mulberry-silk-embroidered-wrap-skirt-set__fudge-2.jpg", "images/products/mulberry-silk-embroidered-wrap-skirt-set__fudge-3.jpg"],
    imagesByColor: {
      "Fudge": ["images/products/mulberry-silk-embroidered-wrap-skirt-set__fudge-1.jpg", "images/products/mulberry-silk-embroidered-wrap-skirt-set__fudge-2.jpg", "images/products/mulberry-silk-embroidered-wrap-skirt-set__fudge-3.jpg"],
      "Chocolate Truffle": ["images/products/mulberry-silk-embroidered-wrap-skirt-set__chocolate-truffle-1.jpg", "images/products/mulberry-silk-embroidered-wrap-skirt-set__chocolate-truffle-2.jpg", "images/products/mulberry-silk-embroidered-wrap-skirt-set__chocolate-truffle-3.jpg"],
    },
    launchedAt: "2026-01-15",
    name: "Mulberry Silk Embroidered Wrap Skirt Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 585,
    colors: ["Fudge", "Chocolate Truffle"],
    length: "Calf",
    bestSeller: false,
    description: "A wrap skirt set finished with hand embroidery, pairing quiet craftsmanship with an easy silhouette.",
  },
  {
    slug: "mulberry-silk-embroidered-v-neck-top",
    images: ["images/products/mulberry-silk-embroidered-v-neck-top__chocolate-truffle-1.jpg", "images/products/mulberry-silk-embroidered-v-neck-top__chocolate-truffle-2.jpg", "images/products/mulberry-silk-embroidered-v-neck-top__chocolate-truffle-3.jpg"],
    imagesByColor: {
      "Chocolate Truffle": ["images/products/mulberry-silk-embroidered-v-neck-top__chocolate-truffle-1.jpg", "images/products/mulberry-silk-embroidered-v-neck-top__chocolate-truffle-2.jpg", "images/products/mulberry-silk-embroidered-v-neck-top__chocolate-truffle-3.jpg"],
      "Fudge": ["images/products/mulberry-silk-embroidered-v-neck-top__fudge-1.jpg", "images/products/mulberry-silk-embroidered-v-neck-top__fudge-2.jpg", "images/products/mulberry-silk-embroidered-v-neck-top__fudge-3.jpg"],
    },
    launchedAt: "2026-02-20",
    name: "Mulberry Silk Embroidered V-Neck Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 320,
    colors: ["Chocolate Truffle", "Fudge"],
    length: "Regular",
    bestSeller: false,
    description: "A V-neck top with hand embroidery along the neckline, adding subtle detail to a clean shape.",
  },
  {
    slug: "mulberry-silk-embroidered-raglan-cut-top",
    images: ["images/products/mulberry-silk-embroidered-raglan-cut-top__white-alyssum-1.jpg", "images/products/mulberry-silk-embroidered-raglan-cut-top__white-alyssum-2.jpg"],
    imagesByColor: {
      "White Alyssum": ["images/products/mulberry-silk-embroidered-raglan-cut-top__white-alyssum-1.jpg", "images/products/mulberry-silk-embroidered-raglan-cut-top__white-alyssum-2.jpg"],
    },
    launchedAt: "2026-07-14",
    name: "Mulberry Silk Embroidered Raglan Cut Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 340,
    colors: ["White Alyssum"],
    length: "Regular",
    bestSeller: false,
    description: "A raglan-cut top with embroidered detailing, offering ease of movement through the shoulder.",
  },
  {
    slug: "mulberry-silk-embroidered-long-top",
    images: ["images/products/mulberry-silk-embroidered-long-top__white-alyssum-1.jpg", "images/products/mulberry-silk-embroidered-long-top__white-alyssum-2.jpg", "images/products/mulberry-silk-embroidered-long-top__white-alyssum-3.jpg"],
    imagesByColor: {
      "White Alyssum": ["images/products/mulberry-silk-embroidered-long-top__white-alyssum-1.jpg", "images/products/mulberry-silk-embroidered-long-top__white-alyssum-2.jpg", "images/products/mulberry-silk-embroidered-long-top__white-alyssum-3.jpg"],
    },
    launchedAt: "2026-07-22",
    name: "Mulberry Silk Embroidered Long Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 300,
    colors: ["White Alyssum"],
    length: "Regular",
    bestSeller: false,
    description: "An elongated embroidered top designed to layer over trousers or skirts for a finished look.",
  },
  {
    slug: "mulberry-silk-embroidered-dress",
    images: ["images/products/mulberry-silk-embroidered-dress__forest-night-1.jpg", "images/products/mulberry-silk-embroidered-dress__forest-night-2.jpg", "images/products/mulberry-silk-embroidered-dress__forest-night-3.jpg"],
    imagesByColor: {
      "Forest Night": ["images/products/mulberry-silk-embroidered-dress__forest-night-1.jpg", "images/products/mulberry-silk-embroidered-dress__forest-night-2.jpg", "images/products/mulberry-silk-embroidered-dress__forest-night-3.jpg"],
      "Duffel Bag": ["images/products/mulberry-silk-embroidered-dress__duffel-bag-1.jpg", "images/products/mulberry-silk-embroidered-dress__duffel-bag-2.jpg", "images/products/mulberry-silk-embroidered-dress__duffel-bag-3.jpg"],
      "Chocolate Truffle": ["images/products/mulberry-silk-embroidered-dress__chocolate-truffle-1.jpg", "images/products/mulberry-silk-embroidered-dress__chocolate-truffle-2.jpg", "images/products/mulberry-silk-embroidered-dress__chocolate-truffle-3.jpg"],
    },
    launchedAt: "2026-07-29",
    name: "Mulberry Silk Embroidered Dress",
    category: "Dresses",
    fabric: "Handwoven Silk",
    price: 355,
    colors: ["Forest Night", "Duffel Bag", "Chocolate Truffle"],
    length: "Calf",
    bestSeller: false,
    description: "An embroidered dress in handwoven silk, cut for a refined silhouette suited to both work and evening.",
  },
  {
    slug: "mulberry-silk-embroidered-cap-sleeve-top",
    images: ["images/products/mulberry-silk-embroidered-cap-sleeve-top__sky-captain-1.jpg", "images/products/mulberry-silk-embroidered-cap-sleeve-top__sky-captain-2.jpg", "images/products/mulberry-silk-embroidered-cap-sleeve-top__sky-captain-3.jpg"],
    imagesByColor: {
      "Sky Captain": ["images/products/mulberry-silk-embroidered-cap-sleeve-top__sky-captain-1.jpg", "images/products/mulberry-silk-embroidered-cap-sleeve-top__sky-captain-2.jpg", "images/products/mulberry-silk-embroidered-cap-sleeve-top__sky-captain-3.jpg"],
      "White Alyssum": ["images/products/mulberry-silk-embroidered-cap-sleeve-top__white-alyssum-1.jpg", "images/products/mulberry-silk-embroidered-cap-sleeve-top__white-alyssum-2.jpg", "images/products/mulberry-silk-embroidered-cap-sleeve-top__white-alyssum-3.jpg"],
    },
    launchedAt: "2026-08-02",
    name: "Mulberry Silk Embroidered Cap Sleeve Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Sky Captain", "White Alyssum"],
    length: "Regular",
    bestSeller: false,
    description: "A cap-sleeve top with embroidered trim, light enough for warm days and polished enough for the office.",
  },
  {
    slug: "mulberry-silk-embroidered-boat-wrap-skirt-set",
    images: ["images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__forest-night-1.jpg", "images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__forest-night-2.jpg", "images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__forest-night-3.jpg"],
    imagesByColor: {
      "Forest Night": ["images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__forest-night-1.jpg", "images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__forest-night-2.jpg", "images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__forest-night-3.jpg"],
      "Fig": ["images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__fig-1.jpg", "images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__fig-2.jpg", "images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__fig-3.jpg"],
      "Duffel Bag": ["images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__duffel-bag-1.jpg", "images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__duffel-bag-2.jpg", "images/products/mulberry-silk-embroidered-boat-wrap-skirt-set__duffel-bag-3.jpg"],
    },
    launchedAt: "2026-08-05",
    name: "Mulberry Silk Embroidered Boat Wrap Skirt Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 700,
    colors: ["Forest Night", "Fig", "Duffel Bag"],
    length: "Calf",
    bestSeller: false,
    description: "A boat-neck top and wrap skirt set with embroidered detailing, the most elevated piece in the collection.",
  },
  {
    slug: "mulberry-silk-embroidered-boat-neck-top",
    images: ["images/products/mulberry-silk-embroidered-boat-neck-top__forest-night-1.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__forest-night-2.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__forest-night-3.jpg"],
    imagesByColor: {
      "Forest Night": ["images/products/mulberry-silk-embroidered-boat-neck-top__forest-night-1.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__forest-night-2.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__forest-night-3.jpg"],
      "Pure Cashmere": ["images/products/mulberry-silk-embroidered-boat-neck-top__pure-cashmere-1.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__pure-cashmere-2.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__pure-cashmere-3.jpg"],
      "Duffel Bag": ["images/products/mulberry-silk-embroidered-boat-neck-top__duffel-bag-1.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__duffel-bag-2.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__duffel-bag-3.jpg"],
      "Fig": ["images/products/mulberry-silk-embroidered-boat-neck-top__fig-1.jpg", "images/products/mulberry-silk-embroidered-boat-neck-top__fig-2.jpg"],
    },
    launchedAt: "2026-08-09",
    name: "Mulberry Silk Embroidered Boat Neck Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 380,
    colors: ["Forest Night", "Pure Cashmere", "Duffel Bag", "Fig"],
    length: "Regular",
    bestSeller: false,
    description: "A boat-neck top with embroidered detailing along the neckline, designed as a statement layering piece.",
  },
];

// Attach sizes + slugs to every product in one place so data entries above stay short.
PRODUCTS.forEach((product) => {
  product.sizes = SIZES;
  product.categorySlug = slugify(product.category);
  product.fabricSlug = slugify(product.fabric);
});

/**
 * Swatch colour for each colour name in the catalog.
 *
 * These are the brand's own values, read from the swatches on eighth-hour.com,
 * not approximations -- the names are Pantone-style marketing names ("Fudge",
 * "Sky Captain") that cannot be guessed from the words. An earlier hand-written
 * map covered 3 of the 17 colours actually in the catalog and invented eight
 * that do not exist in it, so every real product rendered its variants as the
 * same fallback grey and the swatches told the customer nothing.
 *
 * Keyed lowercase so lookups are case- and whitespace-insensitive.
 */
const COLOR_HEXES = {
  "burnt russet": "#7e3940",
  "chocolate truffle": "#612e35",
  "duffel bag": "#394034",
  "ebony": "#2f3136",
  "fig": "#532d3b",
  "forest night": "#29291f",
  "fudge": "#493338",
  "kombu green": "#3a4032",
  "moonless night": "#000000",
  "nomad": "#b49f89",
  "pageant blue": "#171e2e",
  "potent purple": "#462639",
  "pure cashmere": "#b1a699",
  "purple potion": "#692746",
  "sepia tint": "#8e7a66",
  "sky captain": "#393c47",
  "white alyssum": "#ece8e4",
};

/**
 * Hex for a colour name. Falls back to a neutral so an unmapped colour still
 * renders a swatch rather than nothing -- but warns, because a silent fallback
 * is exactly how every product ended up showing identical grey squares.
 */
function colorHex(name) {
  const key = String(name).trim().toLowerCase();
  const hex = COLOR_HEXES[key];
  if (!hex) {
    console.warn(`No swatch colour defined for "${name}" — add it to COLOR_HEXES in js/data.js`);
    return "#b9b2a6";
  }
  return hex;
}
