/**
 * data.js
 * Single source of truth for the product catalog and site navigation.
 * Every page reads from PRODUCTS instead of hard-coding product info,
 * so adding/editing a product only requires changing this one file.
 */

// Sizes offered on every product (matches the real site's XXS-XXL range).
const SIZES = ["XXS", "XS", "S", "M", "L", "XL", "XXL"];

// Categories and fabrics shown in the navigation, in display order.
const CATEGORIES = ["Tops", "Skirts", "Dresses", "Trousers", "Vests", "Co-ord Sets"];
const FABRICS = ["Handwoven Silk", "Natural Crepe"];

// Helper to turn a display name into a URL-safe slug, e.g. "Co-ord Sets" -> "co-ord-sets"
function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const PRODUCTS = [
  // ---- Natural Crepe collection (best sellers) ----
  {
    slug: "crepe-silk-pintuck-straight-skirt",
    name: "Crepe Silk Pintuck Straight Skirt",
    category: "Skirts",
    fabric: "Natural Crepe",
    price: 255,
    colors: ["Pageant Blue"],
    length: "Calf",
    bestSeller: true,
    description: "A straight-cut skirt in soft crepe with fine pintuck detailing at the waist for a clean, tailored line that moves easily from desk to dinner.",
  },
  {
    slug: "crepe-silk-pleated-dress",
    name: "Crepe Silk Pleated Dress",
    category: "Dresses",
    fabric: "Natural Crepe",
    price: 270,
    colors: ["Pageant Blue", "Potent Purple", "Purple Potion"],
    length: "Knee",
    bestSeller: true,
    description: "A sleeveless crepe dress with soft pleats at the bust that release into a gentle flare, striking a balance between everyday ease and evening polish.",
  },
  {
    slug: "crepe-silk-textured-long-top",
    name: "Crepe Silk Textured Long Top",
    category: "Tops",
    fabric: "Natural Crepe",
    price: 320,
    colors: ["Pageant Blue", "Kombu Green"],
    length: "Regular",
    bestSeller: true,
    description: "An elongated top in textured crepe designed to layer cleanly under a blazer or stand alone with tailored trousers.",
  },
  {
    slug: "crepe-silk-vest",
    name: "Crepe Silk Vest",
    category: "Vests",
    fabric: "Natural Crepe",
    price: 225,
    colors: ["Pageant Blue"],
    length: "Regular",
    bestSeller: true,
    description: "A structured crepe vest cut for effortless layering, equally at home over a shirt or worn on its own.",
  },
  {
    slug: "crepe-silk-vest-and-skirt-set",
    name: "Crepe Silk Vest and Skirt Set",
    category: "Co-ord Sets",
    fabric: "Natural Crepe",
    price: 475,
    colors: ["Pageant Blue"],
    length: "Calf",
    bestSeller: false,
    description: "A coordinated vest and skirt in matching crepe, built as a one-decision outfit for days that run long.",
  },

  // ---- Handwoven Silk collection ----
  {
    slug: "mulberry-silk-overlap-vest-and-pintuck-trouser-set",
    name: "Mulberry Silk Overlap Vest and Pintuck Trouser Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 465,
    colors: ["Chocolate Truffle", "Sky Captain", "Fig", "Fudge"],
    length: "Regular",
    bestSeller: false,
    description: "An overlap vest paired with pintuck trousers, both cut from handwoven mulberry silk for a considered head-to-toe look.",
  },
  {
    slug: "mulberry-silk-asymmetrical-wrap-skirt",
    name: "Mulberry Silk Asymmetrical Wrap Skirt",
    category: "Skirts",
    fabric: "Handwoven Silk",
    price: 320,
    colors: ["Forest Night", "Nomad", "Duffel Bag", "Fig"],
    length: "Calf",
    bestSeller: false,
    description: "A wrap skirt with an asymmetrical hem in handwoven silk, offering movement without sacrificing a tailored silhouette.",
  },
  {
    slug: "mulberry-silk-wide-neck-vest-and-pant-set",
    name: "Mulberry Silk Wide Neck Vest and Pant Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 490,
    colors: ["Pure Cashmere", "Duffel Bag", "Ebony"],
    length: "Regular",
    bestSeller: false,
    description: "A wide-neck vest and matching pant in handwoven silk, designed as a single grab-and-go set for packed weeks.",
  },
  {
    slug: "mulberry-silk-vest-and-skirt-set",
    name: "Mulberry Silk Vest and Skirt Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 420,
    colors: ["Burnt Russet", "Nomad"],
    length: "Calf",
    bestSeller: false,
    description: "A vest and skirt set in handwoven silk, pairing a fitted top half with a fluid, easy-moving skirt.",
  },
  {
    slug: "mulberry-silk-vest",
    name: "Mulberry Silk Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 200,
    colors: ["Burnt Russet", "Sepia Tint", "Nomad"],
    length: "Regular",
    bestSeller: false,
    description: "A simply cut vest in handwoven mulberry silk, meant to be worn on repeat under jackets or alone.",
  },
  {
    slug: "mulberry-silk-v-neck-top-with-kantha-embroidery",
    name: "Mulberry Silk V-Neck Top with Kantha Embroidery",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 290,
    colors: ["Pure Cashmere"],
    length: "Regular",
    bestSeller: false,
    description: "A V-neck top finished with hand-stitched kantha embroidery, adding quiet texture to a minimal silhouette.",
  },
  {
    slug: "mulberry-silk-pintuck-cap-sleeve-top",
    name: "Mulberry Silk Pintuck Cap Sleeve Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Chocolate Truffle"],
    length: "Regular",
    bestSeller: false,
    description: "A cap-sleeve top with pintuck detail at the shoulder, cut from handwoven silk for a soft structured drape.",
  },
  {
    slug: "mulberry-silk-pintuck-wrap-skirt",
    name: "Mulberry Silk Pintuck Wrap Skirt",
    category: "Skirts",
    fabric: "Handwoven Silk",
    price: 270,
    colors: ["Fudge", "Chocolate Truffle", "Ebony"],
    length: "Calf",
    bestSeller: false,
    description: "A wrap skirt with pintuck detailing at the waistband, designed to sit smoothly under a fitted top.",
  },
  {
    slug: "mulberry-silk-pintuck-wide-neck-vest",
    name: "Mulberry Silk Pintuck Wide Neck Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Forest Night", "Pure Cashmere", "Duffel Bag", "Ebony"],
    length: "Regular",
    bestSeller: false,
    description: "A wide-neck vest with fine pintuck detailing, cut for a clean line across the shoulders.",
  },
  {
    slug: "mulberry-silk-pintuck-vest",
    name: "Mulberry Silk Pintuck Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Sky Captain"],
    length: "Regular",
    bestSeller: false,
    description: "A pintuck vest in handwoven silk, built as an easy layer over tops and dresses alike.",
  },
  {
    slug: "mulberry-silk-pintuck-trousers",
    name: "Mulberry Silk Pintuck Trousers",
    category: "Trousers",
    fabric: "Handwoven Silk",
    price: 270,
    colors: [
      "Chocolate Truffle", "Ebony", "Forest Night", "Pure Cashmere",
      "Moonless Night", "Nomad", "Fig", "Fudge", "Duffel Bag", "Sky Captain",
    ],
    length: "Cropped",
    bestSeller: false,
    description: "Cropped pintuck trousers in handwoven silk, cut with a tailored waist and a relaxed leg.",
  },
  {
    slug: "mulberry-silk-pintuck-straight-skirt",
    name: "Mulberry Silk Pintuck Straight Skirt",
    category: "Skirts",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Burnt Russet", "Sky Captain", "Nomad"],
    length: "Knee",
    bestSeller: false,
    description: "A straight skirt with pintuck detail at the waist, offering a polished line for the office and beyond.",
  },
  {
    slug: "mulberry-silk-pintuck-overlap-vest",
    name: "Mulberry Silk Pintuck Overlap Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 215,
    colors: ["Ebony", "Moonless Night", "Pure Cashmere"],
    length: "Regular",
    bestSeller: false,
    description: "An overlap-front vest with pintuck detailing, designed to layer neatly over fitted tops.",
  },
  {
    slug: "mulberry-pintuck-vest-and-skirt-set",
    name: "Mulberry Pintuck Vest and Skirt Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 440,
    colors: ["Sky Captain"],
    length: "Calf",
    bestSeller: false,
    description: "A matching pintuck vest and skirt set, made as a single considered outfit for busy days.",
  },
  {
    slug: "mulberry-silk-overlap-vest",
    name: "Mulberry Silk Overlap Vest",
    category: "Vests",
    fabric: "Handwoven Silk",
    price: 200,
    colors: ["Chocolate Truffle", "Sky Captain", "Fudge", "Fig"],
    length: "Regular",
    bestSeller: false,
    description: "An overlap-front vest in handwoven silk, simple enough to wear year-round.",
  },
  {
    slug: "mulberry-silk-overlap-pintuck-vest-and-trouser-set",
    name: "Mulberry Silk Overlap Pintuck Vest and Trouser Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 475,
    colors: ["Ebony", "Moonless Night", "Pure Cashmere"],
    length: "Regular",
    bestSeller: false,
    description: "An overlap vest and pintuck trouser set in handwoven silk, built as a complete look in one order.",
  },
  {
    slug: "mulberry-silk-embroidered-wrap-skirt-set",
    name: "Mulberry Silk Embroidered Wrap Skirt Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 585,
    colors: ["Fudge", "Chocolate Truffle"],
    length: "Calf",
    bestSeller: false,
    description: "A wrap skirt set finished with hand embroidery, pairing quiet craftsmanship with an easy silhouette.",
  },
  {
    slug: "mulberry-silk-embroidered-v-neck-top",
    name: "Mulberry Silk Embroidered V-Neck Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 320,
    colors: ["Chocolate Truffle", "Fudge"],
    length: "Regular",
    bestSeller: false,
    description: "A V-neck top with hand embroidery along the neckline, adding subtle detail to a clean shape.",
  },
  {
    slug: "mulberry-silk-embroidered-raglan-cut-top",
    name: "Mulberry Silk Embroidered Raglan Cut Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 340,
    colors: ["White Alyssum"],
    length: "Regular",
    bestSeller: false,
    description: "A raglan-cut top with embroidered detailing, offering ease of movement through the shoulder.",
  },
  {
    slug: "mulberry-silk-embroidered-long-top",
    name: "Mulberry Silk Embroidered Long Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 300,
    colors: ["White Alyssum"],
    length: "Regular",
    bestSeller: false,
    description: "An elongated embroidered top designed to layer over trousers or skirts for a finished look.",
  },
  {
    slug: "mulberry-silk-embroidered-dress",
    name: "Mulberry Silk Embroidered Dress",
    category: "Dresses",
    fabric: "Handwoven Silk",
    price: 355,
    colors: ["Forest Night", "Duffel Bag", "Chocolate Truffle"],
    length: "Calf",
    bestSeller: false,
    description: "An embroidered dress in handwoven silk, cut for a refined silhouette suited to both work and evening.",
  },
  {
    slug: "mulberry-silk-embroidered-cap-sleeve-top",
    name: "Mulberry Silk Embroidered Cap Sleeve Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 225,
    colors: ["Sky Captain", "White Alyssum"],
    length: "Regular",
    bestSeller: false,
    description: "A cap-sleeve top with embroidered trim, light enough for warm days and polished enough for the office.",
  },
  {
    slug: "mulberry-silk-embroidered-boat-wrap-skirt-set",
    name: "Mulberry Silk Embroidered Boat Wrap Skirt Set",
    category: "Co-ord Sets",
    fabric: "Handwoven Silk",
    price: 700,
    colors: ["Forest Night", "Fig", "Duffel Bag"],
    length: "Calf",
    bestSeller: false,
    description: "A boat-neck top and wrap skirt set with embroidered detailing, the most elevated piece in the collection.",
  },
  {
    slug: "mulberry-silk-embroidered-boat-neck-top",
    name: "Mulberry Silk Embroidered Boat Neck Top",
    category: "Tops",
    fabric: "Handwoven Silk",
    price: 380,
    colors: ["Forest Night", "Pure Cashmere", "Duffel Bag", "Fig"],
    length: "Regular",
    bestSeller: false,
    description: "A boat-neck top with embroidered detailing along the neckline, designed as a statement layering piece.",
  },
];

// Attach sizes + slugs to every product in one place so data entries above stay short.
PRODUCTS.forEach((product) => {
  product.sizes = SIZES;
  product.categorySlug = slugify(product.category);
  product.fabricSlug = slugify(product.fabric);
});
